### ISSUE TITLE
Error when running on chrome

### ISSUE THREAD

**Issue by adalidda** [afzalali15/online_shopee#1]
Hi,

I git clone this tutorial and when run it, I got the following error:

PS C:\src\online_shopee> flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
../flutter/.pub-cache/hosted/pub.dartlang.org/get_navigation-3.12.0/lib/src/extension_navigation.dart:462:37: Error: No named parameter with the name 'shadowThemeOnly'.
    final theme = Theme.of(context, shadowThemeOnly: true);
                                    ^^^^^^^^^^^^^^^
../flutter/packages/flutter/lib/src/material/theme.dart:107:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^
../flutter/.pub-cache/hosted/pub.dartlang.org/get_navigation-3.12.0/lib/src/extension_navigation.dart:655:43: Error: No named parameter with the name 'shadowThemeOnly'.
      theme: Theme.of(key.currentContext, shadowThemeOnly: true),
                                          ^^^^^^^^^^^^^^^
../flutter/packages/flutter/lib/src/material/theme.dart:107:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {

Please help.

Thank You
Adalidda

**Comment by officialismailshah** [comment]
same issue
you are facing this on chrome 
i am facing this on android device

**Comment by officialismailshah** [comment]
> Hi,
> 
> I git clone this tutorial and when run it, I got the following error:
> 
> PS C:\src\online_shopee> flutter run -d chrome
> Launching lib\main.dart on Chrome in debug mode...
> ../flutter/.pub-cache/hosted/pub.dartlang.org/get_navigation-3.12.0/lib/src/extension_navigation.dart:462:37: Error: No named parameter with the name 'shadowThemeOnly'.
> final theme = Theme.of(context, shadowThemeOnly: true);
> ^^^^^^^^^^^^^^^
> ../flutter/packages/flutter/lib/src/material/theme.dart:107:20: Context: Found this candidate, but the arguments don't match.
> static ThemeData of(BuildContext context) {
> ^^
> ../flutter/.pub-cache/hosted/pub.dartlang.org/get_navigation-3.12.0/lib/src/extension_navigation.dart:655:43: Error: No named parameter with the name 'shadowThemeOnly'.
> theme: Theme.of(key.currentContext, shadowThemeOnly: true),
> ^^^^^^^^^^^^^^^
> ../flutter/packages/flutter/lib/src/material/theme.dart:107:20: Context: Found this candidate, but the arguments don't match.
> static ThemeData of(BuildContext context) {
> 
> Please help.
> 
> Thank You
> Adalidda

Hi Adalidda,
I figured out that issue is in the Afzal sir code, I copy and paste the code in the new project which I made by flutter create command and it run.
Regards: Proismailshah

**Comment by adalidda** [comment]
Thank You so much @proismailshah
